name: Collect

on:
  schedule:
    - cron: "0 15 * * *"  # 15:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_vsce_show:
    name: vscode marketplace query
    permissions:
      contents: write # for git to git push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 20

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: '18'
         cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
         go-version: '1.20'
         check-latest: true
         cache: true

      - name: Run vsce show
        run: |
          npm ci
          go run ./tools/run_vsce_show >> data/vscode_marketplace.csv
          tail -n 1 data/vscode_marketplace.csv

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./data/*.csv
          git commit -m "daily update"
          git remote -v
          git push
          git log -1